import os
import re
import vertexai
from vertexai.generative_models import GenerativeModel

# Setup credentials
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = os.path.expandvars(r"%APPDATA%\gcloud\application_default_credentials.json")
PROJECT_ID = "finsight-484914"
LOCATION = "asia-east1" 

def extract_python_code(text):
    """Helper macro to pull out just the python code from the AI's markdown response"""
    match = re.search(r'```python\n(.*?)```', text, re.DOTALL)
    if match:
        return match.group(1).strip()
    return text.strip()

def test_agentic_report_generation(target_format="xlsx"):
    print(f"\n--- TESTING AGENTIC CODE GENERATION ({target_format.upper()}) ---")
    
    # Map the requested format to the correct Python library
    library_map = {
        "xlsx": "openpyxl",
        "docx": "python-docx (import docx)",
        "pptx": "python-pptx (import pptx)"
    }
    required_library = library_map.get(target_format, "openpyxl")
    
    # 1. Simulating Data pulled from Django GLTransaction table
    raw_data = '''
    [
        {"account": "Revenue", "amount": 25000, "type": "Credit"},
        {"account": "Travel Expense", "amount": 7700, "type": "Debit"},
        {"account": "Office Supplies", "amount": 1200, "type": "Debit"},
        {"account": "IT & Software", "amount": 250, "type": "Debit"},
        {"account": "Net Income", "amount": 15850, "type": "Total"}
    ]
    '''

    system_instruction = f"""
    You are an expert Python data engineer. Your job is to write a complete, standalone Python script.
    You must use the '{required_library}' library to construct the document.
    
    CRITICAL SECURITY RULES:
    - Do NOT import os, sys, or subprocess.
    - DO NOT provide any text explanation. ONLY output the raw Python code wrapped in ```python ... ```
    
    The code must save the file exactly as 'agentic_output.{target_format}'.
    """

    model = GenerativeModel(
        "gemini-2.5-pro",
        system_instruction=[system_instruction]
    )

    # dynamically adjust the instructions based on the file type
    if target_format == "xlsx":
        user_instructions = """
        Write a script that creates an Excel workbook. It should feature a dark blue header row with white text.
        Parse the JSON data string provided and loop through it to populate the rows. Highlight the 'Net Income' row in neon green.
        """
    elif target_format == "pptx":
        user_instructions = """
        Write a script that creates a PowerPoint presentation. 
        Slide 1: Title slide saying "August Financials".
        Slide 2: A bulleted list slide summarizing the JSON data provided.
        Slide 3: A bar chart slide visually representing the expenses from the JSON data.
        """
    elif target_format == "docx":
        user_instructions = """
        Write a script that creates a Word document. 
        Add a title "August Income Statement" centered and bold.
        Underneath, parse the JSON data and create a 3-column table containing the Account, Amount, and Type.
        """

    user_prompt = f"""
    Here is the JSON data string representing August expenses:
    {raw_data}
    
    Task: {user_instructions}
    """

    print("Sending prompt and data to Gemini. Writing code...\n")
    response = model.generate_content(user_prompt)
    
    print("[AI Response Received. Extracting Code...]")
    generated_code = extract_python_code(response.text)
    
    print("\n--- GENERATED CODE ---\n")
    print(generated_code)
    print("\n----------------------")
    
    print("\n[Executing Code locally via exec()...]")
    try:
        # DANGEROUS IN PROD: We use exec() here strictly for the MVP local test!
        # In Google Cloud, this code block would be sent to a separate isolated Container.
        exec(generated_code)
        
        if os.path.exists(f'agentic_output.{target_format}'):
            print(f"\n✅ SUCCESS! 'agentic_output.{target_format}' was completely generated by AI and saved to your folder.")
    except Exception as e:
        print(f"\n❌ Execution Failed: {e}")

if __name__ == "__main__":
    print("Ensure you have 'openpyxl', 'python-docx', and 'python-pptx' installed before running this!")
    
    # You can change this to "docx", "pptx", or "xlsx" to test the different engines
    test_agentic_report_generation(target_format="docx")
