# Generated by Django 5.2.7 on 2026-03-09 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company_policydoc_content_text_alter_policydoc_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporttemplate',
            old_name='type',
            new_name='format',
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='data_filters_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GLAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gl_accounts', to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='GLTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_transactions', to='api.claim')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gl_transactions', to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='GLTransactionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_lines', to='api.glaccount')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='api.gltransaction')),
            ],
        ),
    ]
