# Generated by Django 5.2.7 on 2026-03-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_type_reporttemplate_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetpool',
            name='group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
