# Generated by Django 5.2.7 on 2026-03-13 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_budgetpool_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreport',
            name='title',
            field=models.CharField(blank=True, help_text='AI derived title for this report', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CustomStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Detailed payload formatted by AI for injecting into prompts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_styles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
