from django.db import models
from django.contrib.auth.models import AbstractUser

class Company(models.Model):
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class User(AbstractUser):
    ROLE_CHOICES = (
        ('employee', 'Employee'),
        ('admin', 'Admin'),
    )
    role = models.CharField(max_length=20, choices=ROLE_CHOICES, default='employee')
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True, blank=True, related_name='users')

    def __str__(self):
        return self.username

class BudgetPool(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True, blank=True, related_name='budget_pools')
    name = models.CharField(max_length=255)
    start_date = models.DateField()
    end_date = models.DateField()
    total_budget_hkd = models.DecimalField(max_digits=12, decimal_places=2)
    remaining_hkd = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.pk and self.remaining_hkd == 0:
            self.remaining_hkd = self.total_budget_hkd
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

class Claim(models.Model):
    STATUS_CHOICES = (
        ('pending', 'Pending'),
        ('approved', 'Approved'),
        ('rejected', 'Rejected'),
        ('returned', 'Returned'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='claims')
    budget_pool = models.ForeignKey(BudgetPool, on_delete=models.SET_NULL, null=True, blank=True, related_name='active_claims')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    amount_hkd = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    merchant = models.CharField(max_length=255, null=True, blank=True)
    date = models.DateField(null=True, blank=True)
    category = models.CharField(max_length=255, null=True, blank=True)
    note = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Claim #{self.id} by {self.user}"

class ReceiptFile(models.Model):
    claim = models.ForeignKey(Claim, on_delete=models.CASCADE, related_name='receipts')
    url = models.URLField(max_length=1024, null=True, blank=True)
    ocr_json = models.JSONField(null=True, blank=True)
    ocr_confidence = models.FloatField(null=True, blank=True)
    
    def __str__(self):
        return f"Receipt for Claim #{self.claim_id}"

class Approval(models.Model):
    claim = models.ForeignKey(Claim, on_delete=models.CASCADE, related_name='approvals')
    approver = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='decisions')
    decision = models.CharField(max_length=20)
    comment = models.TextField(null=True, blank=True)
    decided_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Approval for Claim #{self.claim_id}"

class PolicyDoc(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True, blank=True, related_name='policies')
    title = models.CharField(max_length=255)
    version = models.CharField(max_length=50)
    url = models.URLField(max_length=1024, null=True, blank=True)
    content_text = models.TextField(help_text="Raw text for Vertex AI RAG", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class ReportTemplate(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True, blank=True, related_name='templates')
    name = models.CharField(max_length=255)
    format = models.CharField(max_length=50) # 'pptx', 'docx', 'xlsx'
    data_filters_json = models.JSONField(null=True, blank=True)
    config_json = models.JSONField()
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class GeneratedReport(models.Model):
    template = models.ForeignKey(ReportTemplate, on_delete=models.CASCADE, null=True, blank=True, related_name='generated_reports')
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='generated_reports')
    file_url = models.URLField(max_length=1024)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Report {self.id} generated by {self.user}"

class ChatSession(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='chat_sessions')
    context = models.CharField(max_length=50, help_text="'employee' or 'admin'")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Session {self.id} for {self.user.username}"

class ChatMessage(models.Model):
    session = models.ForeignKey(ChatSession, on_delete=models.CASCADE, related_name='messages')
    role = models.CharField(max_length=20, help_text="'user' or 'model'")
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Message {self.id} by {self.role}"

class GLAccount(models.Model):
    ACCOUNT_TYPES = (
        ('asset', 'Asset'),
        ('liability', 'Liability'),
        ('equity', 'Equity'),
        ('revenue', 'Revenue'),
        ('expense', 'Expense'),
    )
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='gl_accounts')
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=50) # e.g., "1000", "5000"
    account_type = models.CharField(max_length=20, choices=ACCOUNT_TYPES)

    def __str__(self):
        return f"[{self.code}] {self.name}"

class GLTransaction(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='gl_transactions')
    date = models.DateField()
    description = models.CharField(max_length=255)
    claim = models.ForeignKey(Claim, on_delete=models.SET_NULL, null=True, blank=True, related_name='gl_transactions')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Txn #{self.id} on {self.date}"

class GLTransactionLine(models.Model):
    transaction = models.ForeignKey(GLTransaction, on_delete=models.CASCADE, related_name='lines')
    account = models.ForeignKey(GLAccount, on_delete=models.PROTECT, related_name='ledger_lines')
    debit = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    credit = models.DecimalField(max_digits=12, decimal_places=2, default=0)

    def __str__(self):
        return f"Line for Txn {self.transaction_id} - {self.account.name}"