from datetime import date
import json

# Placeholder imports - uncomment when environment is ready with credentials
# from google.cloud import documentai
# from google.cloud import storage
# import vertexai
# from vertexai.preview.language_models import ChatModel
# from pptx import Presentation
# from docx import Document

class OCRService:
    @staticmethod
    def extract_receipt(file_path):
        """
        Wraps google-cloud-documentai to process receipts.
        Takes a file path (or bytes), uploads to GCS (optional), sends to DocAI.
        Returns extracted JSON fields.
        """
        # TODO: Implement Actual Document AI call
        # Mock response for MVP skeletal phase
        return {
            "merchant": "Starbucks HK",
            "date": "2023-10-25",
            "amount": 48.0,
            "currency": "HKD",
            "category": "Meals",
            "items": ["Latte", "Bagel"]
        }

class ChatbotService:
    @staticmethod
    def generate_response(message, context="employee"):
        """
        Wraps vertexai to handle chat prompts.
        Context can be 'employee' (policy Q&A) or 'admin' (report help).
        """
        # TODO: Implement Vertex AI ChatModel
        return f"Hello, I am the {context} chatbot. You said: '{message}'. (AI Integration Pending)"

class ReportChatService:
    @staticmethod
    def refine_report_config(user_prompt, current_config=None):
        """
        Specialized chatbot flow to iteratively design reports. 
        It uses Vertex AI to generate/update a structured JSON configuration 
        (slides, titles, bullet points) based on user prompts.
        """
        if not current_config:
            current_config = {
                "title": "Monthly Expense Report",
                "slides": []
            }
        
        # TODO: Use LLM to intelligently merge user_prompt into current_config
        # Mock logic: Add a new slide for every prompt
        new_slide = {
            "title": f"Section: {user_prompt}",
            "content": ["Bullet point 1", "Bullet point 2 generated by AI"]
        }
        current_config["slides"].append(new_slide)
        
        return current_config

class ReportGeneratorService:
    @staticmethod
    def generate_pptx(config_json, output_path):
        """
        Takes the JSON configuration from ReportChatService and uses python-pptx
        to render the actual binary file.
        """
        # TODO: Implement python-pptx logic
        # prs = Presentation()
        # ... build slides ...
        # prs.save(output_path)
        pass

    @staticmethod
    def generate_docx(config_json, output_path):
        """
        Takes the JSON configuration and renders a .docx file.
        """
        # TODO: Implement python-docx logic
        pass
